server:
  port: 8081

# 项目的相关配置
spring:
  # 服务名
  application:
    name: authorization-server

encrypt:
  key-store:
    location: classpath:/tcm.jks
    alias: tcm
    password: tcmpass
    secret: tcmpass
