server:
  port: 8081

# 项目的相关配置
spring:
  # 服务名
  application:
    name: authorization-server
  security:
    user:
      # 认证使用的用户名
      name: admin
      # 认证使用的密码
      password: 123456

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    # 是否优先使用IP地址作为主机名的标识，默认为false
    prefer-ip-address: true
    # 客户端向服务端发送心跳（服务续约任务）的调用时间间隔，默认为30秒
    lease-renewal-interval-in-seconds: 30
    # 服务端在收到最后一次心跳之后的等待时间上限（服务时效的时间），默认为90秒
    lease-expiration-duration-in-seconds: 90
