server:
  port: 8000

# 项目的相关配置
spring:
  # 服务名
  application:
    name: gateway-server
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          # 设置允许跨域的路径
          '[/**]':
            # 允许所有访问源地址
            allowedOrigins: "*"
            # 允许所有请求方式
            allowedMethods: "*"
            # 允许所有请求头
            allowedHeaders: "*"
            # 设置响应报头，不能使用*号
            exposedHeaders: "token, Content-Type, Content-Disposition"
            # 是否允许证书，不再默认开启
            allowCredentials: true
            # 设置允许跨域时间为1800s
            maxAge: 1800
      # 必须加上StripPrefix=1，否则访问服务时会带上tool，而不是我们期望的去掉tool，只保留**部分
      default-filters:
      - StripPrefix=1
      routes:
      # 配置一个路由名字，可任意命名
      - id: tool_route
        # 必须使用http进行转发，lb代表从注册中心获取服务
        uri: lb://tool-service
        # 转发该路径中包含/tool/**的请求到tool-service服务
        predicates:
        - Path=/tool/**

eureka:
  instance:
    instance-id: ${eureka.instance.ip-address}:${server.port}
    # 是否优先使用IP地址作为主机名的标识，默认为false
    prefer-ip-address: true
    # 客户端向服务端发送心跳（服务续约任务）的调用时间间隔，默认为30秒
    lease-renewal-interval-in-seconds: 30
    # 服务端在收到最后一次心跳之后的等待时间上限（服务时效的时间），默认为90秒
    lease-expiration-duration-in-seconds: 90
